"""empty message

Revision ID: 18f771bf7cb1
Revises: bbbb2dcfdbd0
Create Date: 2024-05-14 12:13:24.387037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f771bf7cb1'
down_revision = 'bbbb2dcfdbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=False))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_final', sa.Boolean(), nullable=False))

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seconds', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('answer', sa.String(length=50), nullable=False))
        batch_op.drop_column('attempts')
        batch_op.drop_column('miliseconds')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('miliseconds', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('attempts', sa.INTEGER(), nullable=False))
        batch_op.drop_column('answer')
        batch_op.drop_column('is_correct')
        batch_op.drop_column('seconds')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('is_final')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###
