"""Initial migration

Revision ID: bbbb2dcfdbd0
Revises: 
Create Date: 2024-01-14 12:40:47.162953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbbb2dcfdbd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.drop_column('last_name')
        batch_op.drop_column('last_name_2')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('last_name_2', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=15), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
